version: "3.8"
services:
  app:
    container_name: php_contactform
    build: ./docker/php
    volumes:
      - ./src:/contactform

  web:
    container_name: nginx_contactform
    image: nginx:1.18-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/contactform
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /contactform
